title: Chú Đại Bi
description: >-
  Chú Đại Bi, trích từ bộ Kinh Nhật Tụng của chùa Hoằng Pháp.
  Nguồn: https://www.chuahoangphap.com.vn/thu-vien-kinh-sach/chi-tiet-kinh-nhat-tung-166/
github_username:  tiennm99
theme: minima
